# Generated by Django 5.1.4 on 2024-12-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='comments',
            name='likeCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='likeCount',
            field=models.IntegerField(default=0),
        ),
    ]
