# Generated by Django 5.1.4 on 2024-12-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0002_rename_author_comments_user_alter_comments_likecount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='likeCount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='likeCount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
