# Generated by Django 5.1.4 on 2024-12-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0003_alter_comments_likecount_alter_post_likecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='likeCount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='likeCount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
