# Generated by Django 5.1.4 on 2024-12-17 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0007_post_userid_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='userId',
            new_name='user',
        ),
    ]
