# Generated by Django 5.1.4 on 2024-12-19 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0011_post_newcomments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='newComments',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='post',
        ),
    ]
