# Generated by Django 5.1.4 on 2024-12-12 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
